--liquibase formatted sql

--*******************************************************************
--changeset hollywood:1 dbms:postgresql
CREATE TABLE director (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);
--rollback drop table director;

--*******************************************************************
-- Models one to one relationship. Each movie has 1 director
--changeset hollywood:2 dbms:postgresql
CREATE TABLE movie (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  title TEXT NOT NULL,
  director_id INT NOT NULL REFERENCES director(id),
  release_year INT NOT NULL
);
--rollback drop table movie;

--*******************************************************************
--changeset hollywood:3 dbms:postgresql
CREATE TABLE actor (
  id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  name TEXT NOT NULL
);
--rollback drop table actor;

--*******************************************************************
-- Models many to many relationship using a join table.
-- A movie can have many actors, and an actor can be in many movies
--changeset hollywood:4 dbms:postgresql
CREATE TABLE actor_movie (
  PRIMARY KEY (actor_id, movie_id),
  actor_id INT NOT NULL REFERENCES actor(id),
  movie_id INT NOT NULL REFERENCES movie(id)
);
--rollback drop table actor_movie;
