--liquibase formatted sql

-- Attribution note: Example database is from Learning PostgresSQL 11 by Salahaldin Juba and Andrey Volkov

--*******************************************************************
--changeset carstore:1 dbms:postgresql
CREATE TABLE account (
  account_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT NOT NULL,
  last_name TEXT NOT NULL,
  email TEXT NOT NULL UNIQUE,
  password TEXT NOT NULL,
  CHECK(first_name !~ '\s' AND last_name !~ '\s'),
  CHECK (email ~* '^\w+@\w+[.]\w+$'),
  CHECK (char_length(password)>=8)
);
--rollback drop table account;

--*******************************************************************
-- Models one to one relationship
--changeset carstore:2 dbms:postgresql
CREATE TABLE seller_account (
  seller_account_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  account_id INT NOT NULL REFERENCES account(account_id),
  total_rank FLOAT,
  number_of_advertisement INT,
  street_name TEXT NOT NULL,
  street_number TEXT NOT NULL,
  zip_code TEXT NOT NULL,
  city TEXT NOT NULL
);
--rollback drop table seller_account;

--*******************************************************************
--changeset carstore:3 dbms:postgresql
CREATE TABLE car(
 car_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 price FLOAT NOT NULL,
 make TEXT,
 model TEXT,
 model_year SMALLINT
);
--rollback drop table car;

--*******************************************************************
-- Models one to many relationship
--changeset carstore:4 dbms:postgresql
CREATE TABLE advertisement(
 advertisement_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
 advertisement_date TIMESTAMP WITH TIME ZONE NOT NULL,
 car_id INT NOT NULL REFERENCES car(car_id),
 seller_account_id INT NOT NULL REFERENCES seller_account (seller_account_id)
);
--rollback drop table advertisement;

--*******************************************************************
-- Models many to many relationship using a join table
--changeset carstore:5 dbms:postgresql
CREATE TABLE favorite_advertisement(
  PRIMARY KEY (account_id,advertisement_id),
  account_id INT NOT NULL REFERENCES account(account_id),
  advertisement_id INT NOT NULL REFERENCES advertisement(advertisement_id)
);
--rollback drop table favorite_advertisement;
